apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kwite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /kwite
        backend:
          serviceName: kwite
          servicePort: 8080
